[program:vnc]
command=/opt/pibot/bin/start-vnc.sh
user=abc
priority=10
autostart=true
autorestart=true
stdout_logfile=/tmp/vnc.log
stderr_logfile=/tmp/vnc.log

[program:xfce]
command=/opt/pibot/bin/start-xfce.sh
user=abc
priority=20
autostart=true
autorestart=true
stdout_logfile=/tmp/xfce.log
stderr_logfile=/tmp/xfce.log

[program:computer]
command=/opt/pibot/bin/start-service.sh
user=abc
priority=40
autostart=true
autorestart=true
stdout_logfile=/tmp/pibot-computer.log
stderr_logfile=/tmp/pibot-computer.log

[program:novnc]
command=/opt/pibot/bin/start-novnc.sh
user=root
priority=50
autostart=true
autorestart=true
stdout_logfile=/tmp/novnc.log
stderr_logfile=/tmp/novnc.log
