[program:screens]
command=/opt/pibot/bin/start-screens.sh
user=abc
priority=10
autostart=true
autorestart=true
stdout_logfile=/tmp/screens.log
stderr_logfile=/tmp/screens.log

[program:computer]
command=/opt/pibot/bin/start-service.sh
user=abc
priority=40
autostart=true
autorestart=true
stdout_logfile=/tmp/pibot-computer.log
stderr_logfile=/tmp/pibot-computer.log
